# Generated by Django 5.2.13 on 2026-04-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rutas_asignadas',
            field=models.ManyToManyField(blank=True, related_name='empleados_asignados', to='rutas.ruta'),
        ),
    ]
