# Generated by Django 5.2.13 on 2026-04-24 02:02

import django.core.validators
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_alter_encomienda_codigo_alter_encomienda_peso_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo, django.core.validators.MinValueValidator(0.01, message='El peso mínimo es 0.01 kg')]),
        ),
    ]
