# Generated by Django 5.2.13 on 2026-05-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_alter_encomienda_costo_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteQuerySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
