# Generated by Django 5.2.13 on 2026-04-24 01:56

import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nro_doc',
            field=models.CharField(max_length=15, unique=True, validators=[envios.validators.validar_nro_doc_dni]),
        ),
    ]
